### ISSUE TITLE
Particle and Weaponart shuffled

### ISSUE THREAD

**Issue by ScooterSasha** [arthurb123/ERregulator#1]
Particles were shuffled without the checkbox active.

Weaponmovesets were shuffled outside their pools (club with shield moveset), checkbox "keep categories" was checked.

Any idea how to keep patricles and movesets in the original state?

**Comment by arthurb123** [comment]
Hello,

All melee weapons (this includes shields) are seen as a single category. Therefore, with the "Keep Categories" option checked, clubs and shields can share move sets, stats, etc. If you would like, I could add an option to exclude shields from the melee category.

What do you mean exactly with particles? Which checkbox did you uncheck?

**Comment by ScooterSasha** [comment]
Shields excluded is fine, but keeping all movesets would be my plan. (AoW shuffle is fine)

Following checkboxes were not activated: spells, projectiles, others, no limits, humans, goods.
Still the starting club had some strange fire effects and a hitbox that hit enemies behind several walls/floors

**Comment by arthurb123** [comment]
Gotcha, I can add options for keeping move sets/allowing arts of war shuffling as well.

I think what you were encountering was that, the weapon had its move set and possibly other variables shuffled, making the club you were using function as it did (e.g: longer reach, weird hit box, fire effects upon impact normally only caused by certain weapons). This is because the goal of the randomizer is to shuffle all kinds of parameters, resulting in weird and surprising effects and results.

**Comment by ScooterSasha** [comment]
I was afraid that moveset shuffle is somehow tied to scaling shuffle 

If you can provide those additional Options it would be amazing.

**Comment by arthurb123** [comment]
I added the new options in b63fd485a916205f2441e14fb938ed52704103f2. The [new release](https://github.com/arthurb123/ERregulator/releases/tag/v1.1) under the version number 1.1 includes the new options. I have tested it, and it seems to all work fine. However, if you experience any issues with the new options, let me know!

**Comment by ScooterSasha** [comment]
Well, seems like windows is detecting some "wacatac" malware now and wont let me handle your file

**Comment by arthurb123** [comment]
That is weird. I have run [virus total](https://www.virustotal.com/gui/file/42a06e816bcfbb319f4ca1ffb95020084b19013e342477adadd80b9ea08dba95) on the 1.1 release and some virus scanners do indeed flag it as a virus. However, I believe these to be false positives as the detections were made using machine learning and only have a moderate confidence (e.g: _MachineLearning/Anomalous.95%_ by Malwarebytes). 

I am not sure if I can do anything about this, besides waiting for the virus scanners to get updated and hopefully not flag it anymore. There are two solutions you can take at the moment;
1. Make an exception in your virus scanner, but I can totally understand if you are not comfortable with this option - as you would have to believe me that the release is safe;
2. Or build the project from the source. This requires some technical know-how as you would have to clone the repository and follow the steps on [building the project from the source code](https://github.com/arthurb123/ERregulator?tab=readme-ov-file#building-from-source). By building the project from the source code, you can be sure that no viruses will be present in the final binary executable.

I'm sorry for the inconvenience, but I can't do more than this.

**Comment by ScooterSasha** [comment]
No need to be sorry. I'm pretty surprised by the support you gave me just to improve my gaming experience!

I'm optimistic to solve the virus thing myself somehow to make it work

**Comment by arthurb123** [comment]
Well, I got some good news. I figured out what is causing the false positive, there were some old packages in the project that weren't used anymore but somehow triggered the flagging. I have removed them and updated the release, can you try downloading the [v1.1 release](https://github.com/arthurb123/ERregulator/releases/tag/v1.1) again?

**Comment by ScooterSasha** [comment]
Still the same Error for me

**Comment by arthurb123** [comment]
That's unfortunate, I was confident that would fix it, as it now only shows one detection instead of four on [virus total](https://www.virustotal.com/gui/file/213e64a3b009c223db9f5cdcc97b7e2b8211f22b1005ad5c1333170ab47102c4). It was a good attempt, but then that's all I can do. If you do manage to get the program running and have any questions or issues, let me know! :)

**Comment by ScooterSasha** [comment]
A friend got it working, no virus detection at all for him

Anyways, on randomizing he got following pretty long error message:

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'SoulsFormats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'SoulsFormats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ERregulator.FormMain.Randomize(IProgress`1 progress)
   at ERregulator.FormMain.<btnRandomize_Click>b__9_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ERregulator.FormMain.<btnRandomize_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ERregulator
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1
    CodeBase: file:///D:/SteamLibrary/steamapps/common/ELDEN%20RING/ERregulator.v1.1/ERregulator.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by arthurb123** [comment]
Ah, that's an issue on my part, I know what is going wrong. I'll fix it later today and let you know once I have updated the release!

**Comment by arthurb123** [comment]
I fixed the issue, can you download the new [v1.1 release](https://github.com/arthurb123/ERregulator/releases/tag/v1.1) and try it out?

**Comment by aiandev** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
arnauoller, @Raefey, @cristoferdomingues, @ChinW, @jnathn, @warrichrepos, @urkl, @almondsz, @doyonghoon, @etochavez, @cityblack1, @judefort, @Aledon8, @logikinc, @Zeretal, @Armand-Morin, @brokerexio, @lpcteste, @goofyww, @llenroc

**Comment by LeonardoWlopes** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
NJRca, @LetSwiftDev, @kucar, @dunci, @cleett, @renwoox, @kaiterm, @cryptoTOM97, @donewiththedollar, @xiaomin0322, @derorin, @0xCoeus, @tolgakurtuluss, @gifgiif, @cheehong1229, @muratakcs, @ktkization, @tonyshao80, @HAOYUatHZ, @tarmylan

**Comment by ScooterSasha** [comment]
Movesets seem to be working now, including shield

Still having some wierd AoE hitboxes and particle effects on weapons,

**Comment by arthurb123** [comment]
Good to hear! Unfortunately that is just how this randomizer operates, it shuffles in-game parameters resulting in weird and unexpected behavior that one would not get from a "regular" randomizer. The hit boxes and particle effects are probably caused by randomization through other (default) options.

**Comment by ScooterSasha** [comment]
https://github.com/arthurb123/ERregulator/assets/160402426/d420457a-5e58-4395-87d8-23d3284d4b0c

This still happens in very few caves, never in Open world, hitting enemies far away.

No clue why, but playable i would say
